version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: mr-code-fixer
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: pefman
    name: Mr-Code-Fixer
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  header: |
    ## Mr. Code Fixer v{{.Version}}
    
    Automated GitHub issue fixing using AI! 🤖
    
    ### Installation
    
    Download the binary for your platform below, or use:
    
    ```bash
    go install github.com/pefman/mr-code-fixer@{{.Tag}}
    ```
    
  footer: |
    ### What's Changed
    
    See the full changelog below.
    
    **Full Changelog**: https://github.com/pefman/Mr-Code-Fixer/compare/{{.PreviousTag}}...{{.Tag}}

brews:
  - repository:
      owner: pefman
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/pefman/Mr-Code-Fixer
    description: Automated GitHub issue fixing using AI
    license: MIT
    skip_upload: auto
